const TEMPLATE_LIBRARY = [
  {
    id: "saas_dark",
    name: "Dark SaaS",
    header: "sticky",
    hero: "center",
    about: "two-column",
    services: "cards",
    whyUs: "stats",
    testimonials: "grid",
    faq: "accordion",
    gallery: "masonry",
    cta: "gradient",
    footer: "mega"
  },
  {
    id: "saas_light",
    name: "Light SaaS",
    header: "transparent",
    hero: "split",
    about: "image-right",
    services: "cards",
    whyUs: "icon-grid",
    testimonials: "carousel",
    faq: "grid",
    gallery: "carousel",
    cta: "solid",
    footer: "simple"
  },
  {
    id: "agency_modern",
    name: "Modern Agency",
    header: "floating",
    hero: "split",
    about: "story",
    services: "large-cards",
    whyUs: "cards",
    testimonials: "grid",
    faq: "tabs",
    gallery: "showcase",
    cta: "gradient",
    footer: "four-column"
  },
  {
    id: "agency_luxury",
    name: "Luxury Agency",
    header: "minimal",
    hero: "center",
    about: "image-left",
    services: "minimal",
    whyUs: "checklist",
    testimonials: "quotes",
    faq: "list",
    gallery: "grid",
    cta: "glass",
    footer: "newsletter"
  },
  {
    id: "startup_pitch",
    name: "Startup Pitch",
    header: "solid",
    hero: "dashboard",
    about: "timeline",
    services: "icons",
    whyUs: "features",
    testimonials: "grid",
    faq: "two-column",
    gallery: "slider",
    cta: "gradient",
    footer: "minimal"
  },
  {
    id: "tech_product",
    name: "Technology Product",
    header: "centered",
    hero: "split",
    about: "split",
    services: "feature-grid",
    whyUs: "stats",
    testimonials: "cards",
    faq: "accordion",
    gallery: "masonry",
    cta: "gradient",
    footer: "mega"
  },
  {
    id: "portfolio_creator",
    name: "Creator Portfolio",
    header: "sticky",
    hero: "image-left",
    about: "two-column",
    services: "timeline",
    whyUs: "icon-grid",
    testimonials: "quotes",
    faq: "grid",
    gallery: "carousel",
    cta: "solid",
    footer: "simple"
  },
  {
    id: "portfolio_designer",
    name: "Designer Portfolio",
    header: "transparent",
    hero: "gallery",
    about: "image-right",
    services: "grid",
    whyUs: "cards",
    testimonials: "minimal",
    faq: "tabs",
    gallery: "showcase",
    cta: "glass",
    footer: "four-column"
  },
  {
    id: "restaurant_modern",
    name: "Restaurant",
    header: "floating",
    hero: "image-background",
    about: "story",
    services: "menu-grid",
    whyUs: "checklist",
    testimonials: "cards",
    faq: "list",
    gallery: "grid",
    cta: "gradient",
    footer: "newsletter"
  },
  {
    id: "fitness_brand",
    name: "Fitness",
    header: "minimal",
    hero: "video-style",
    about: "image-left",
    services: "cards",
    whyUs: "features",
    testimonials: "grid",
    faq: "two-column",
    gallery: "slider",
    cta: "gradient",
    footer: "minimal"
  },
  {
    id: "construction",
    name: "Construction",
    header: "solid",
    hero: "bold",
    about: "timeline",
    services: "large-cards",
    whyUs: "stats",
    testimonials: "grid",
    faq: "accordion",
    gallery: "masonry",
    cta: "solid",
    footer: "mega"
  },
  {
    id: "real_estate",
    name: "Real Estate",
    header: "centered",
    hero: "image-right",
    about: "split",
    services: "cards",
    whyUs: "icon-grid",
    testimonials: "carousel",
    faq: "grid",
    gallery: "carousel",
    cta: "glass",
    footer: "simple"
  },
  {
    id: "law_firm",
    name: "Law Firm",
    header: "sticky",
    hero: "professional",
    about: "two-column",
    services: "minimal",
    whyUs: "cards",
    testimonials: "quotes",
    faq: "tabs",
    gallery: "showcase",
    cta: "solid",
    footer: "four-column"
  },
  {
    id: "medical_clinic",
    name: "Medical",
    header: "transparent",
    hero: "clean",
    about: "image-right",
    services: "cards",
    whyUs: "checklist",
    testimonials: "grid",
    faq: "list",
    gallery: "grid",
    cta: "gradient",
    footer: "newsletter"
  },
  {
    id: "dentist",
    name: "Dentist",
    header: "floating",
    hero: "split",
    about: "story",
    services: "feature-grid",
    whyUs: "features",
    testimonials: "cards",
    faq: "two-column",
    gallery: "slider",
    cta: "gradient",
    footer: "minimal"
  },
  {
    id: "automotive",
    name: "Automotive",
    header: "minimal",
    hero: "image-background",
    about: "image-left",
    services: "cards",
    whyUs: "stats",
    testimonials: "grid",
    faq: "accordion",
    gallery: "masonry",
    cta: "solid",
    footer: "mega"
  },
  {
    id: "ecommerce_modern",
    name: "Ecommerce",
    header: "solid",
    hero: "product-showcase",
    about: "timeline",
    services: "product-grid",
    whyUs: "icon-grid",
    testimonials: "cards",
    faq: "grid",
    gallery: "carousel",
    cta: "gradient",
    footer: "simple"
  },
  {
    id: "fashion_brand",
    name: "Fashion",
    header: "centered",
    hero: "editorial",
    about: "split",
    services: "gallery",
    whyUs: "cards",
    testimonials: "minimal",
    faq: "tabs",
    gallery: "showcase",
    cta: "glass",
    footer: "four-column"
  },
  {
    id: "beauty_brand",
    name: "Beauty",
    header: "sticky",
    hero: "image-focus",
    about: "two-column",
    services: "cards",
    whyUs: "checklist",
    testimonials: "quotes",
    faq: "list",
    gallery: "grid",
    cta: "gradient",
    footer: "newsletter"
  },
  {
    id: "coffee_shop",
    name: "Coffee Shop",
    header: "transparent",
    hero: "background-photo",
    about: "image-right",
    services: "menu-grid",
    whyUs: "features",
    testimonials: "cards",
    faq: "two-column",
    gallery: "slider",
    cta: "solid",
    footer: "minimal"
  },
  {
    id: "bakery",
    name: "Bakery",
    header: "floating",
    hero: "image-focus",
    about: "story",
    services: "cards",
    whyUs: "stats",
    testimonials: "grid",
    faq: "accordion",
    gallery: "masonry",
    cta: "gradient",
    footer: "mega"
  },
  {
    id: "event_company",
    name: "Events",
    header: "minimal",
    hero: "gallery",
    about: "image-left",
    services: "cards",
    whyUs: "icon-grid",
    testimonials: "quotes",
    faq: "grid",
    gallery: "carousel",
    cta: "gradient",
    footer: "simple"
  },
  {
    id: "photography",
    name: "Photography",
    header: "solid",
    hero: "full-image",
    about: "timeline",
    services: "gallery",
    whyUs: "cards",
    testimonials: "minimal",
    faq: "tabs",
    gallery: "showcase",
    cta: "glass",
    footer: "four-column"
  },
  {
    id: "nonprofit",
    name: "Nonprofit",
    header: "centered",
    hero: "story",
    about: "split",
    services: "impact-grid",
    whyUs: "checklist",
    testimonials: "quotes",
    faq: "list",
    gallery: "grid",
    cta: "solid",
    footer: "newsletter"
  },
  {
    id: "church",
    name: "Church",
    header: "sticky",
    hero: "welcoming",
    about: "two-column",
    services: "community-grid",
    whyUs: "features",
    testimonials: "quotes",
    faq: "two-column",
    gallery: "slider",
    cta: "solid",
    footer: "minimal"
  },
  {
    id: "cybersecurity",
    name: "Cybersecurity",
    header: "transparent",
    hero: "dark-tech",
    about: "image-right",
    services: "security-grid",
    whyUs: "stats",
    testimonials: "cards",
    faq: "accordion",
    gallery: "masonry",
    cta: "neon",
    footer: "mega"
  },
  {
    id: "hosting_company",
    name: "Hosting Company",
    header: "floating",
    hero: "server-dashboard",
    about: "story",
    services: "pricing-grid",
    whyUs: "icon-grid",
    testimonials: "cards",
    faq: "grid",
    gallery: "carousel",
    cta: "gradient",
    footer: "simple"
  },
  {
    id: "ai_startup",
    name: "AI Startup",
    header: "minimal",
    hero: "futuristic",
    about: "image-left",
    services: "feature-grid",
    whyUs: "cards",
    testimonials: "carousel",
    faq: "tabs",
    gallery: "showcase",
    cta: "glass",
    footer: "four-column"
  },
  {
    id: "web_design_agency",
    name: "Web Design Agency",
    header: "solid",
    hero: "showcase",
    about: "timeline",
    services: "portfolio-grid",
    whyUs: "checklist",
    testimonials: "quotes",
    faq: "list",
    gallery: "grid",
    cta: "gradient",
    footer: "newsletter"
  },
  {
    id: "marketing_agency",
    name: "Marketing Agency",
    header: "centered",
    hero: "conversion",
    about: "split",
    services: "cards",
    whyUs: "features",
    testimonials: "grid",
    faq: "two-column",
    gallery: "slider",
    cta: "gradient",
    footer: "minimal"
  },
  {
    id: "seo_company",
    name: "SEO Company",
    header: "sticky",
    hero: "growth-chart",
    about: "two-column",
    services: "feature-grid",
    whyUs: "stats",
    testimonials: "cards",
    faq: "accordion",
    gallery: "masonry",
    cta: "solid",
    footer: "mega"
  },
  {
    id: "consulting",
    name: "Consulting",
    header: "transparent",
    hero: "executive",
    about: "image-right",
    services: "minimal",
    whyUs: "icon-grid",
    testimonials: "quotes",
    faq: "grid",
    gallery: "carousel",
    cta: "glass",
    footer: "simple"
  },
  {
    id: "accounting",
    name: "Accounting",
    header: "floating",
    hero: "professional",
    about: "story",
    services: "cards",
    whyUs: "cards",
    testimonials: "grid",
    faq: "tabs",
    gallery: "showcase",
    cta: "solid",
    footer: "four-column"
  },
  {
    id: "insurance",
    name: "Insurance",
    header: "minimal",
    hero: "trust",
    about: "image-left",
    services: "cards",
    whyUs: "checklist",
    testimonials: "carousel",
    faq: "list",
    gallery: "grid",
    cta: "solid",
    footer: "newsletter"
  },
  {
    id: "education",
    name: "Education",
    header: "solid",
    hero: "learning",
    about: "timeline",
    services: "course-grid",
    whyUs: "features",
    testimonials: "cards",
    faq: "two-column",
    gallery: "slider",
    cta: "gradient",
    footer: "minimal"
  },
  {
    id: "online_course",
    name: "Online Course",
    header: "centered",
    hero: "instructor",
    about: "split",
    services: "lesson-grid",
    whyUs: "stats",
    testimonials: "quotes",
    faq: "accordion",
    gallery: "masonry",
    cta: "gradient",
    footer: "mega"
  },
  {
    id: "university",
    name: "University",
    header: "sticky",
    hero: "campus",
    about: "two-column",
    services: "info-grid",
    whyUs: "icon-grid",
    testimonials: "cards",
    faq: "grid",
    gallery: "carousel",
    cta: "solid",
    footer: "simple"
  },
  {
    id: "travel_agency",
    name: "Travel Agency",
    header: "transparent",
    hero: "destination",
    about: "image-right",
    services: "gallery",
    whyUs: "cards",
    testimonials: "cards",
    faq: "tabs",
    gallery: "showcase",
    cta: "gradient",
    footer: "four-column"
  },
  {
    id: "hotel",
    name: "Hotel",
    header: "floating",
    hero: "luxury-photo",
    about: "story",
    services: "amenities-grid",
    whyUs: "checklist",
    testimonials: "carousel",
    faq: "list",
    gallery: "grid",
    cta: "glass",
    footer: "newsletter"
  },
  {
    id: "resort",
    name: "Resort",
    header: "minimal",
    hero: "beachfront",
    about: "image-left",
    services: "gallery",
    whyUs: "features",
    testimonials: "quotes",
    faq: "two-column",
    gallery: "slider",
    cta: "glass",
    footer: "minimal"
  },
  {
    id: "gaming",
    name: "Gaming",
    header: "solid",
    hero: "esports",
    about: "timeline",
    services: "cards",
    whyUs: "stats",
    testimonials: "community",
    faq: "accordion",
    gallery: "masonry",
    cta: "neon",
    footer: "mega"
  },
  {
    id: "esports_team",
    name: "Esports Team",
    header: "centered",
    hero: "arena",
    about: "split",
    services: "roster-grid",
    whyUs: "icon-grid",
    testimonials: "community",
    faq: "grid",
    gallery: "carousel",
    cta: "neon",
    footer: "simple"
  },
  {
    id: "music_artist",
    name: "Music Artist",
    header: "sticky",
    hero: "album-cover",
    about: "two-column",
    services: "media-grid",
    whyUs: "cards",
    testimonials: "fan-quotes",
    faq: "tabs",
    gallery: "showcase",
    cta: "glass",
    footer: "four-column"
  },
  {
    id: "podcast",
    name: "Podcast",
    header: "transparent",
    hero: "studio",
    about: "image-right",
    services: "episode-grid",
    whyUs: "checklist",
    testimonials: "listener-cards",
    faq: "list",
    gallery: "grid",
    cta: "gradient",
    footer: "newsletter"
  },
  {
    id: "author",
    name: "Author",
    header: "floating",
    hero: "book-showcase",
    about: "story",
    services: "publication-grid",
    whyUs: "features",
    testimonials: "quotes",
    faq: "two-column",
    gallery: "slider",
    cta: "solid",
    footer: "minimal"
  },
  {
    id: "charity",
    name: "Charity",
    header: "minimal",
    hero: "community",
    about: "image-left",
    services: "impact-grid",
    whyUs: "stats",
    testimonials: "stories",
    faq: "accordion",
    gallery: "masonry",
    cta: "solid",
    footer: "mega"
  },
  {
    id: "pet_services",
    name: "Pet Services",
    header: "solid",
    hero: "pet-photo",
    about: "timeline",
    services: "cards",
    whyUs: "icon-grid",
    testimonials: "cards",
    faq: "grid",
    gallery: "carousel",
    cta: "gradient",
    footer: "simple"
  },
  {
    id: "landscaping",
    name: "Landscaping",
    header: "centered",
    hero: "outdoor",
    about: "split",
    services: "gallery",
    whyUs: "cards",
    testimonials: "grid",
    faq: "tabs",
    gallery: "showcase",
    cta: "solid",
    footer: "four-column"
  },
  {
    id: "cleaning_company",
    name: "Cleaning Company",
    header: "sticky",
    hero: "fresh",
    about: "two-column",
    services: "cards",
    whyUs: "checklist",
    testimonials: "quotes",
    faq: "list",
    gallery: "grid",
    cta: "gradient",
    footer: "newsletter"
  },
  {
    id: "moving_company",
    name: "Moving Company",
    header: "transparent",
    hero: "logistics",
    about: "image-right",
    services: "cards",
    whyUs: "features",
    testimonials: "grid",
    faq: "two-column",
    gallery: "slider",
    cta: "solid",
    footer: "minimal"
  },
  {
    id: "plumbing",
    name: "Plumbing",
    header: "floating",
    hero: "service-call",
    about: "story",
    services: "repair-grid",
    whyUs: "stats",
    testimonials: "cards",
    faq: "accordion",
    gallery: "masonry",
    cta: "solid",
    footer: "mega"
  },
  {
    id: "electrician",
    name: "Electrician",
    header: "minimal",
    hero: "power-grid",
    about: "image-left",
    services: "cards",
    whyUs: "icon-grid",
    testimonials: "quotes",
    faq: "grid",
    gallery: "carousel",
    cta: "solid",
    footer: "simple"
  },
  {
    id: "roofing",
    name: "Roofing",
    header: "solid",
    hero: "contractor",
    about: "timeline",
    services: "project-grid",
    whyUs: "cards",
    testimonials: "cards",
    faq: "tabs",
    gallery: "showcase",
    cta: "gradient",
    footer: "four-column"
  },
  {
    id: "hvac",
    name: "HVAC",
    header: "centered",
    hero: "comfort",
    about: "split",
    services: "service-grid",
    whyUs: "checklist",
    testimonials: "cards",
    faq: "list",
    gallery: "grid",
    cta: "solid",
    footer: "newsletter"
  },
  {
    id: "solar_energy",
    name: "Solar Energy",
    header: "sticky",
    hero: "eco-tech",
    about: "two-column",
    services: "feature-grid",
    whyUs: "features",
    testimonials: "grid",
    faq: "two-column",
    gallery: "slider",
    cta: "gradient",
    footer: "minimal"
  },
  {
    id: "cryptocurrency",
    name: "Cryptocurrency",
    header: "transparent",
    hero: "fintech",
    about: "image-right",
    services: "dashboard-grid",
    whyUs: "stats",
    testimonials: "cards",
    faq: "accordion",
    gallery: "masonry",
    cta: "neon",
    footer: "mega"
  },
  {
    id: "fintech",
    name: "Fintech",
    header: "floating",
    hero: "banking-app",
    about: "story",
    services: "feature-grid",
    whyUs: "icon-grid",
    testimonials: "carousel",
    faq: "grid",
    gallery: "carousel",
    cta: "gradient",
    footer: "simple"
  },
  {
    id: "investment_firm",
    name: "Investment Firm",
    header: "minimal",
    hero: "wealth",
    about: "image-left",
    services: "cards",
    whyUs: "cards",
    testimonials: "quotes",
    faq: "tabs",
    gallery: "showcase",
    cta: "solid",
    footer: "four-column"
  },
  {
    id: "stock_trading",
    name: "Stock Trading",
    header: "solid",
    hero: "market-data",
    about: "timeline",
    services: "dashboard-grid",
    whyUs: "checklist",
    testimonials: "cards",
    faq: "list",
    gallery: "grid",
    cta: "gradient",
    footer: "newsletter"
  },
  {
    id: "car_dealership",
    name: "Car Dealership",
    header: "centered",
    hero: "vehicle-showcase",
    about: "split",
    services: "inventory-grid",
    whyUs: "features",
    testimonials: "cards",
    faq: "two-column",
    gallery: "slider",
    cta: "solid",
    footer: "minimal"
  },
  {
    id: "auto_repair",
    name: "Auto Repair",
    header: "sticky",
    hero: "garage",
    about: "two-column",
    services: "repair-grid",
    whyUs: "stats",
    testimonials: "quotes",
    faq: "accordion",
    gallery: "masonry",
    cta: "solid",
    footer: "mega"
  },
  {
    id: "motorcycle_shop",
    name: "Motorcycle Shop",
    header: "transparent",
    hero: "bike-showcase",
    about: "image-right",
    services: "cards",
    whyUs: "icon-grid",
    testimonials: "cards",
    faq: "grid",
    gallery: "carousel",
    cta: "gradient",
    footer: "simple"
  },
  {
    id: "barber_shop",
    name: "Barber Shop",
    header: "floating",
    hero: "modern-barber",
    about: "story",
    services: "pricing-grid",
    whyUs: "cards",
    testimonials: "quotes",
    faq: "tabs",
    gallery: "showcase",
    cta: "solid",
    footer: "four-column"
  },
  {
    id: "salon",
    name: "Hair Salon",
    header: "minimal",
    hero: "beauty-photo",
    about: "image-left",
    services: "cards",
    whyUs: "checklist",
    testimonials: "cards",
    faq: "list",
    gallery: "grid",
    cta: "gradient",
    footer: "newsletter"
  },
  {
    id: "spa",
    name: "Spa",
    header: "solid",
    hero: "relaxation",
    about: "timeline",
    services: "cards",
    whyUs: "features",
    testimonials: "quotes",
    faq: "two-column",
    gallery: "slider",
    cta: "glass",
    footer: "minimal"
  },
  {
    id: "tattoo_studio",
    name: "Tattoo Studio",
    header: "centered",
    hero: "artist-focus",
    about: "split",
    services: "gallery",
    whyUs: "stats",
    testimonials: "cards",
    faq: "accordion",
    gallery: "masonry",
    cta: "dark",
    footer: "mega"
  },
  {
    id: "brewery",
    name: "Brewery",
    header: "sticky",
    hero: "craft-beer",
    about: "two-column",
    services: "menu-grid",
    whyUs: "icon-grid",
    testimonials: "cards",
    faq: "grid",
    gallery: "carousel",
    cta: "solid",
    footer: "simple"
  },
  {
    id: "food_truck",
    name: "Food Truck",
    header: "transparent",
    hero: "street-food",
    about: "image-right",
    services: "menu-grid",
    whyUs: "cards",
    testimonials: "quotes",
    faq: "tabs",
    gallery: "showcase",
    cta: "gradient",
    footer: "four-column"
  },
  {
    id: "catering",
    name: "Catering",
    header: "floating",
    hero: "event-food",
    about: "story",
    services: "cards",
    whyUs: "checklist",
    testimonials: "stories",
    faq: "list",
    gallery: "grid",
    cta: "gradient",
    footer: "newsletter"
  },
  {
    id: "wedding_planner",
    name: "Wedding Planner",
    header: "minimal",
    hero: "romantic",
    about: "image-left",
    services: "timeline",
    whyUs: "features",
    testimonials: "stories",
    faq: "two-column",
    gallery: "slider",
    cta: "glass",
    footer: "minimal"
  },
  {
    id: "daycare",
    name: "Daycare",
    header: "solid",
    hero: "family-friendly",
    about: "timeline",
    services: "cards",
    whyUs: "stats",
    testimonials: "parent-quotes",
    faq: "accordion",
    gallery: "masonry",
    cta: "solid",
    footer: "mega"
  },
  {
    id: "tutoring",
    name: "Tutoring",
    header: "centered",
    hero: "education",
    about: "split",
    services: "subject-grid",
    whyUs: "icon-grid",
    testimonials: "student-quotes",
    faq: "grid",
    gallery: "carousel",
    cta: "gradient",
    footer: "simple"
  },
  {
    id: "language_school",
    name: "Language School",
    header: "sticky",
    hero: "global-learning",
    about: "two-column",
    services: "course-grid",
    whyUs: "cards",
    testimonials: "student-cards",
    faq: "tabs",
    gallery: "showcase",
    cta: "gradient",
    footer: "four-column"
  },
  {
    id: "coworking_space",
    name: "Coworking Space",
    header: "transparent",
    hero: "workspace",
    about: "image-right",
    services: "membership-grid",
    whyUs: "checklist",
    testimonials: "cards",
    faq: "list",
    gallery: "grid",
    cta: "modern",
    footer: "newsletter"
  },
  {
    id: "printing_company",
    name: "Printing Company",
    header: "floating",
    hero: "print-showcase",
    about: "story",
    services: "cards",
    whyUs: "features",
    testimonials: "quotes",
    faq: "two-column",
    gallery: "slider",
    cta: "solid",
    footer: "minimal"
  },
  {
    id: "personal_trainer",
    name: "Personal Trainer",
    header: "minimal",
    hero: "fitness-coach",
    about: "image-left",
    services: "training-grid",
    whyUs: "stats",
    testimonials: "transformation-stories",
    faq: "accordion",
    gallery: "masonry",
    cta: "gradient",
    footer: "mega"
  },
  {
    id: "yoga_studio",
    name: "Yoga Studio",
    header: "solid",
    hero: "wellness",
    about: "timeline",
    services: "class-grid",
    whyUs: "icon-grid",
    testimonials: "quotes",
    faq: "grid",
    gallery: "carousel",
    cta: "glass",
    footer: "simple"
  },
  {
    id: "martial_arts",
    name: "Martial Arts",
    header: "centered",
    hero: "dojo",
    about: "split",
    services: "program-grid",
    whyUs: "cards",
    testimonials: "student-stories",
    faq: "tabs",
    gallery: "showcase",
    cta: "solid",
    footer: "four-column"
  },
  {
    id: "gym",
    name: "Gym",
    header: "sticky",
    hero: "fitness-center",
    about: "two-column",
    services: "membership-grid",
    whyUs: "checklist",
    testimonials: "cards",
    faq: "list",
    gallery: "grid",
    cta: "gradient",
    footer: "newsletter"
  },
  {
    id: "nutritionist",
    name: "Nutritionist",
    header: "transparent",
    hero: "healthy-lifestyle",
    about: "image-right",
    services: "cards",
    whyUs: "features",
    testimonials: "success-stories",
    faq: "two-column",
    gallery: "slider",
    cta: "glass",
    footer: "minimal"
  },
  {
    id: "pharmacy",
    name: "Pharmacy",
    header: "floating",
    hero: "healthcare",
    about: "story",
    services: "service-grid",
    whyUs: "stats",
    testimonials: "cards",
    faq: "accordion",
    gallery: "masonry",
    cta: "solid",
    footer: "mega"
  },
  {
    id: "veterinarian",
    name: "Veterinarian",
    header: "minimal",
    hero: "animal-care",
    about: "image-left",
    services: "cards",
    whyUs: "icon-grid",
    testimonials: "pet-owner-quotes",
    faq: "grid",
    gallery: "carousel",
    cta: "gradient",
    footer: "simple"
  },
  {
    id: "animal_shelter",
    name: "Animal Shelter",
    header: "solid",
    hero: "adoption",
    about: "timeline",
    services: "gallery",
    whyUs: "cards",
    testimonials: "stories",
    faq: "tabs",
    gallery: "showcase",
    cta: "solid",
    footer: "four-column"
  },
  {
    id: "bookstore",
    name: "Bookstore",
    header: "centered",
    hero: "bookshelf",
    about: "split",
    services: "collection-grid",
    whyUs: "checklist",
    testimonials: "reader-reviews",
    faq: "list",
    gallery: "grid",
    cta: "minimal",
    footer: "newsletter"
  },
  {
    id: "library",
    name: "Library",
    header: "sticky",
    hero: "knowledge",
    about: "two-column",
    services: "resource-grid",
    whyUs: "features",
    testimonials: "community-stories",
    faq: "two-column",
    gallery: "slider",
    cta: "solid",
    footer: "minimal"
  },
  {
    id: "museum",
    name: "Museum",
    header: "transparent",
    hero: "exhibition",
    about: "image-right",
    services: "gallery",
    whyUs: "stats",
    testimonials: "visitor-reviews",
    faq: "accordion",
    gallery: "masonry",
    cta: "glass",
    footer: "mega"
  },
  {
    id: "art_gallery",
    name: "Art Gallery",
    header: "floating",
    hero: "creative-showcase",
    about: "story",
    services: "art-grid",
    whyUs: "icon-grid",
    testimonials: "quotes",
    faq: "grid",
    gallery: "carousel",
    cta: "minimal",
    footer: "simple"
  },
  {
    id: "architecture_firm",
    name: "Architecture Firm",
    header: "minimal",
    hero: "building-design",
    about: "image-left",
    services: "project-grid",
    whyUs: "cards",
    testimonials: "client-quotes",
    faq: "tabs",
    gallery: "showcase",
    cta: "luxury",
    footer: "four-column"
  },
  {
    id: "interior_design",
    name: "Interior Design",
    header: "solid",
    hero: "room-showcase",
    about: "timeline",
    services: "gallery",
    whyUs: "checklist",
    testimonials: "stories",
    faq: "list",
    gallery: "grid",
    cta: "luxury",
    footer: "newsletter"
  },
  {
    id: "furniture_store",
    name: "Furniture Store",
    header: "centered",
    hero: "home-design",
    about: "split",
    services: "product-grid",
    whyUs: "features",
    testimonials: "reviews",
    faq: "two-column",
    gallery: "slider",
    cta: "modern",
    footer: "minimal"
  },
  {
    id: "home_builder",
    name: "Home Builder",
    header: "sticky",
    hero: "dream-home",
    about: "two-column",
    services: "project-grid",
    whyUs: "stats",
    testimonials: "homeowner-stories",
    faq: "accordion",
    gallery: "masonry",
    cta: "solid",
    footer: "mega"
  },
  {
    id: "moving_storage",
    name: "Moving & Storage",
    header: "transparent",
    hero: "logistics",
    about: "image-right",
    services: "service-grid",
    whyUs: "icon-grid",
    testimonials: "reviews",
    faq: "grid",
    gallery: "carousel",
    cta: "solid",
    footer: "simple"
  },
  {
    id: "security_company",
    name: "Security Company",
    header: "floating",
    hero: "protection",
    about: "story",
    services: "security-grid",
    whyUs: "cards",
    testimonials: "client-quotes",
    faq: "tabs",
    gallery: "showcase",
    cta: "dark",
    footer: "four-column"
  },
  {
    id: "recruitment_agency",
    name: "Recruitment Agency",
    header: "minimal",
    hero: "career-growth",
    about: "image-left",
    services: "hiring-grid",
    whyUs: "checklist",
    testimonials: "success-stories",
    faq: "list",
    gallery: "grid",
    cta: "modern",
    footer: "newsletter"
  },
  {
    id: "hr_consulting",
    name: "HR Consulting",
    header: "solid",
    hero: "professional-services",
    about: "timeline",
    services: "cards",
    whyUs: "features",
    testimonials: "business-reviews",
    faq: "two-column",
    gallery: "slider",
    cta: "solid",
    footer: "minimal"
  },
  {
    id: "software_company",
    name: "Software Company",
    header: "centered",
    hero: "product-showcase",
    about: "split",
    services: "feature-grid",
    whyUs: "stats",
    testimonials: "customer-cards",
    faq: "accordion",
    gallery: "masonry",
    cta: "gradient",
    footer: "mega"
  },
  {
    id: "mobile_app",
    name: "Mobile App",
    header: "sticky",
    hero: "app-preview",
    about: "two-column",
    services: "feature-grid",
    whyUs: "icon-grid",
    testimonials: "user-reviews",
    faq: "grid",
    gallery: "carousel",
    cta: "gradient",
    footer: "simple"
  },
  {
    id: "streaming_platform",
    name: "Streaming Platform",
    header: "transparent",
    hero: "media-showcase",
    about: "image-right",
    services: "content-grid",
    whyUs: "cards",
    testimonials: "viewer-quotes",
    faq: "tabs",
    gallery: "showcase",
    cta: "dark",
    footer: "four-column"
  },
  {
    id: "community_platform",
    name: "Community Platform",
    header: "floating",
    hero: "social-network",
    about: "story",
    services: "feature-grid",
    whyUs: "checklist",
    testimonials: "member-stories",
    faq: "list",
    gallery: "grid",
    cta: "modern",
    footer: "newsletter"
  },
  {
    id: "news_media",
    name: "News & Media",
    header: "minimal",
    hero: "headline-focus",
    about: "image-left",
    services: "article-grid",
    whyUs: "features",
    testimonials: "reader-quotes",
    faq: "two-column",
    gallery: "slider",
    cta: "minimal",
    footer: "minimal"
  }
];

function getRandomTemplate() {
return TEMPLATE_LIBRARY[
Math.floor(Math.random() * TEMPLATE_LIBRARY.length)
];
}

function getTemplateById(id) {
return TEMPLATE_LIBRARY.find(
template => template.id === id
);
}
